data_platform:
  outputs:
    local:
      catalog: "{{ env_var('catalog', 'main') }}"
      host: loyalty-nz-terraform-databricks-production.cloud.databricks.com
      http_path: "{{ env_var('http_path', 'sql/protocolv1/o/6434335555892652/0426-115902-a2gm8ndg') }}"
      schema: "{{ env_var('schema_prefix', 'test') }}"
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
    dev:
      catalog: "{{ env_var('catalog', 'qual') }}"
      host: loyalty-nz-terraform-databricks-production.cloud.databricks.com
      http_path: "{{ env_var('http_path') }}"
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
    production:
      catalog: "{{ env_var('catalog', 'prod') }}"
      host: loyalty-nz-production.cloud.databricks.com
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
  target: local
