data_platform:
  outputs:
    local:
      catalog: "{{ env_var('catalog', 'main') }}"
      host: loyalty-nz-terraform-databricks-production.cloud.databricks.com
      http_path: "{{ env_var('http_path', '/sql/1.0/warehouses/da02c4849da79e50') }}"
      schema: "{{ env_var('schema_prefix', 'sl') }}"
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
    dev:
      catalog: "{{ env_var('catalog', 'qual') }}"
      host: loyalty-nz-terraform-databricks-production.cloud.databricks.com
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
    production:
      catalog: "{{ env_var('catalog', 'prod') }}"
      host: loyalty-nz-production.cloud.databricks.com
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('databricks_token') }}"
      type: databricks
    predeployment:
      catalog: "{{ env_var('catalog', 'qual') }}"
      host: "{{ env_var('DATABRICKS_HOST_RED') }}"
      http_path: "{{ env_var('http_path', '/sql/1.0/warehouses/86ea17f40dd68256') }}"
      schema: "{{ env_var('schema_prefix', 'clone') }}"
      threads: "{{ env_var('dbt_threads', 20) }}"
      token: "{{ env_var('DATABRICKS_TOKEN_RED') }}"
      type: databricks
  target: local
