# This YAML file defines a github action that we want to use to run DBT Tests
# in Databricks in a safe environment.

# To learn more about YAML, see:
# https://learnxinyminutes.com/docs/yaml/

# To see the reference for the Github Actions, see:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: DBT Testing

on:
  # We want to have two ways of triggering the action.
  # The first will be a manual trigger that is more appropriate for
  # manual testing. This way, we can only trigger the action
  # when we want while we are building it out, and we won't
  # trigger it involuntarily when doing other things in this repo.

  workflow_dispatch:
    # TODO: If we need a variable here for a manual run, we can define it.
    # This can be accessed in the Job as ${{inputs.example}}
    inputs:
      example:
        description: 'This is just a Dummy Input for Manual Runs'
        required: false
        type: string

  # TODO: Once we are happy with the manual runs, we will need to define the github
  # or git actions that will trigger this Github Action .

  #Workflows will not run on pull_request activity if the pull request has a merge conflict.
  #By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - ready_for_review
    branches:
      - main
    paths:
      - 'dp_airflow/dbt/**'

# TODO: Should we have concurrency setting to control how many actions can run in parallel?

# A Job is a set of steps (actions) that run on a specific runner (virtual computer).
# If you have more than one job, they run in parallel by default. See:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobs

jobs:
  dbt-test:
    name: DBT Test
    # Ubuntu Latest has heaps of software installed on it. See:
    # https://github.com/actions/runner-images/blob/ubuntu22/20240804.1/images/ubuntu/Ubuntu2204-Readme.md
    runs-on: ubuntu-latest

    # Each job has Steps - each step has its own process in the runner, so variables are not shared. See:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - name: Echo the Input Just For a Start
        run: |
          echo This is the skeleton of the CICD Task. Our Input is: ${{inputs.example}}

    # TODO: Lets have a step which installs DBT

    # TODO: Lets have a step to checkout the code in the branch we want to update.
    #  (how do we do this with manual input?)

    # TODO: Can we use that code to connect to Databricks?

    # TODO: How can we detect which models have changed?

    # TODO: How can we clone tables using the Databricks APIs for the tests we will run?

    # TODO: How can we run the DBT tests for the models that are updated?

    # TODO: Should we run the DBT tests for downstream tables on clones?

    # TODO: How can we clean up the cloned tables we have created?

    # TODO: How can we fail the github action if the tests fail?
